version: '1.0'

services:
  app:
    build: ./lumina
    ports:
      - "${APP_PORT}:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - MEILISEARCH_URL=${MEILISEARCH_URL}
      - MEILISEARCH_KEY=${MEILISEARCH_KEY}
    depends_on:
      - mongodb
      - meilisearch

  mongodb:
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "${MEILISEARCH_PORT}:7700"
    environment:
      - MEILISEARCH_KEY=${MEILISEARCH_KEY}
    volumes:
      - meilisearch_data:/meili_data

volumes:
  mongodb_data:
  meilisearch_data:
